[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python -m uvicorn main:app --reload --host 0.0.0.0 --port 8000"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
